### ISSUE TITLE
Repository download stops at Openssl in powershell

### ISSUE THREAD

**Issue by Babaloncryptolog** [mmcs85/eos#1]
PS C:\USER\EOS> .\build.ps1

--- Creating EOS external dependencies ---

--- boost 1.65.1 already installed ---

--- gettext-0.19.8 already installed ---

--- zlib 1.2.11 already installed ---

--- bzip2 1.0.6 already installed ---

Configuring openssl 1.1.0

Configuring OpenSSL version 1.1.0h-dev (0x10100080L)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-dynamic-engine [forced]
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-shared       [option]
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib-dynamic [option]
Configuring for VC-WIN64A
NASM not found - please read INSTALL and NOTES.WIN for further details

Building openssl 1.1.0

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
        perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
        perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\nmake.exe" _all

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cc  -I. -Icrypto/include -Iinclude -DNDEBUG -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -O  -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c'cc' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'cc' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

--- openssl 1.1.0 installation failed ---

**Comment by mmcs85** [comment]
You need to install NASM go here: http://www.nasm.us/

**Comment by Babaloncryptolog** [comment]
Nasm is installed however I don't know how to configure it.
Do I need to use a specific start menu folder?

**Comment by mmcs85** [comment]
Can you confirm that NASM is installed on C:\Program Files\NASM and that if you write on powershell $env:path the path for it is on the environment variables?

If not try add in the environment variables the path for nasm folder

**Comment by Babaloncryptolog** [comment]
Ok, it's not showing up under program files what should I do in order to have it show up?

**Comment by mmcs85** [comment]
You may need to reinstall, viewing the openssl logs looks like you have a 64bit windows.
So download the nasm installer: http://www.nasm.us/pub/nasm/releasebuilds/2.13.02/win64/

this version of eos only works on win64 for now anyways.

**Comment by Babaloncryptolog** [comment]
Everything is showing up now. 
However, it's still not wanting to DL OpenSSL. :(

**Comment by mmcs85** [comment]
I need the logs from the console in order to help

**Comment by Babaloncryptolog** [comment]
I'm sorry but I don't understand what you mean by console logs? 
It's saying the same thing I posted earlier.

**Comment by mmcs85** [comment]
Ok then the openssl configuration is not finding the NASM path.Try to close the shell console and run build on a new one to get the new env variables.

**Comment by Babaloncryptolog** [comment]
when I run .\build.ps1 on Powershell it closes as soon as it starts working on Openssl so I can't copy anything down or screenshot it.

**Comment by Babaloncryptolog** [comment]
PowerShell Integrated Console

PS C:\Kyzitemelos93\EOS> .\build.ps1

Visual Studio 2017 Command Prompt variables set.

--- Creating EOS external dependencies ---


--- boost 1.65.1 already installed ---


--- gettext-0.19.8 already installed ---


--- zlib 1.2.11 already installed ---


--- bzip2 1.0.6 already installed ---


Configuring openssl 1.1.0

& : The term 'perl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Kyzitemelos93\EOS\build.ps1:307 char:5
+         & perl configure VC-WIN64A enable-capieng no-shared zlib no-z ...
+           ~~~~
    + CategoryInfo          : ObjectNotFound: (perl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Building openssl 1.1.0


Microsoft (R) Program Maintenance Utility Version 14.12.25834.0
Copyright (C) Microsoft Corporation.  All rights reserved.

install(2) : fatal error U1033: syntax error : 'OPENSSL' unexpected
Stop.

--- openssl 1.1.0 installation failed ---

PS C:\Kyzitemelos93\EOS>

**Comment by mmcs85** [comment]
you need to install perl. (ActivePerl) (https://www.perl.org/)
And after installing open a powershell console and run:
ppm install Archive-Extract

**Comment by Babaloncryptolog** [comment]
PS C:\Windows\system32> ppm install Archive-Extract
ppm : The term 'ppm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ppm install Archive-Extract
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ppm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Babaloncryptolog** [comment]
I installed Perl however it does not open in CMD with the perl-v command.

**Comment by mmcs85** [comment]
Something got wrong on your installation.
Check this article - https://community.activestate.com/forum-topic/ppm-not-recognized

You may need to reinstall and then check in the path env variables if the path to the perl folder is there.

**Comment by mmcs85** [comment]
I'm going to assume you got it working. Feel free to open a new issue.

**Comment by Babaloncryptolog** [comment]
No, I haven't I fixed Perl, however, I still can't get it to install past Openssl.
