### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Dan195** [mmcs85/eos#2]
I am currently getting an error when running `.\build.ps1 `in Powershell. The error is as follows `.\build.ps1 : The term '.\build.ps1' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\build.ps1
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\build.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

This was after running `ppm install Archive-Extract` and cloning the repository as specified on Steem.

**Comment by mmcs85** [comment]
After cloning the git project you need to go the folder where build.ps1 is located.
cd path/to/eos/folder

**Comment by mmcs85** [comment]
I'm going to assume you got it working.

**Comment by Dan195** [comment]
Yes I got it working this morning. Thanks!
