### ISSUE TITLE
bjam.exe is not recognized

### ISSUE THREAD

**Issue by Dan195** [mmcs85/eos#3]
I apologize for the questions as I am new to C++ and Visual Studio,

when running .\build.ps1, boost 1.65.1 is successfully extracted in C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1, but when powershell begins `Building Boost.Build engine` I get the following error

```
.\bjam.exe : The term '.\bjam.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\Peter\Desktop\EOS\eos\build.ps1:145 char:3
         .\bjam.exe runtime-link=shared --threading=multi --variant=de ...
         ~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (.\bjam.exe:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException`
```

I tried searching for bjam.exe, but the only bjam file I can find is the bjam.qbk file in `C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1\tools\build\doc.`

When searching the issue, I found [this](http://www.boost.org/users/download/boost_jam_3_1_18.html)  which seems to indicate the bjam file should be part of the Boost system downloaded and extracted in the first step as this is a post 2010 version, but I cannot find it inside of the extracted boost folder.

**Comment by mmcs85** [comment]
Can you post the full console log? bjam is supposed to be generated when boost is being configured by bootstrap.bat

**Comment by Dan195** [comment]
` C:\Users\Peter\Desktop\EOS\eos> .\build.ps1

--- Creating EOS external dependencies ---

Configuring boost 1.65.1

Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org
Please attach bootstrap.log in that case.

Building boost 1.65.1

.\bjam.exe : The term '.\bjam.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\Peter\Desktop\EOS\eos\build.ps1:145 char:3
         .\bjam.exe runtime-link=shared --threading=multi --variant=de ...
         ~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (.\bjam.exe:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException


--- boost 1.65.1 installation failed ---
`

**Comment by mmcs85** [comment]
Looks like something about your system can you post bootstrap.log? It should give more hints about the problem

**Comment by Dan195** [comment]
Here is my bootstrap.log file...

`###
### Using 'vc141' toolset.
###

C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1\tools\build\src\engine>if exist bootstrap rd /S /Q bootstrap 

C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1\tools\build\src\engine>md bootstrap 

C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1\tools\build\src\engine>cl /nologo /RTC1 /Zi /MTd /Fobootstrap/ /Fdbootstrap/ -DNT -DYYDEBUG -wd4996 kernel32.lib advapi32.lib user32.lib /Febootstrap\jam0  command.c compile.c constants.c debug.c execcmd.c execnt.c filent.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathnt.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c md5.c class.c cwd.c w32_getreg.c native.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c 
command.c
compile.c
constants.c
debug.c
execcmd.c
execnt.c
execnt.c(57): fatal error C1083: Cannot open include file: 'tlhelp32.h': No such file or directory
filent.c
filent.c(488): warning C4477: 'sprintf' : format string '%.*s' requires an argument of type 'int', but variadic argument 1 has type '__int64'
filent.c(488): note: this argument is used as a precision
frames.c
function.c
glob.c
hash.c
hdrmacro.c
headers.c
jam.c
jambase.c
jamgram.c
lists.c
make.c
make1.c
object.c
Generating Code...
Compiling...
option.c
output.c
parse.c
pathnt.c
pathsys.c
regexp.c
rules.c
scan.c
search.c
subst.c
timestamp.c
variable.c
modules.c
strings.c
filesys.c
builtins.c
md5.c
class.c
cwd.c
w32_getreg.c
Generating Code...
Compiling...
native.c
set.c
path.c
regex.c
property-set.c
sequence.c
order.c
Generating Code...

C:\Users\Peter\Desktop\EOS\extdeps\boost_1_65_1\tools\build\src\engine>exit /b 2 
`

**Comment by mmcs85** [comment]
Please don't change boost source code it would break your changes in case you need to upgrade.
This looks like related with the windows SDK version installed with Visual studio.

Please answer this question:
- What is your OS? Windows 10?
- What version of Windows SDK did you install? Windows 10 SDK (10.0.16299.0)?

Refer to my post for help: https://steemit.com/eos/@mmcs/building-eos-with-visual-studio-2017-for-windows-10

**Comment by Dan195** [comment]
@mmcs85 I came here from your post. The .\build.ps1 portion is what led to me needing to find around 5-6 fixes before installation was complete. I was able to do everything else without changing the code, but the t1help32.h file was the only one where I needed to change any code as the solutions online for the problem I was having with t1help32.h indicated that it should've already been working properly, so I changed the code in this one instance.

**Comment by mmcs85** [comment]
Dan195 are you using a x64 or x32 bit system?

**Comment by Dan195** [comment]
I am using an x64. I decided to do a re-install and it went smoothly up until this error with OpenSSL...

`apps\x509.c(912): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
        IF EXIST apps\openssl.exe.manifest DEL /F /Q apps\openssl.exe.manifest
        link /nologo /debug /subsystem:console /opt:ref /out:apps\openssl.exe @C:\Users\Peter\AppData\Local\Temp\nmF083.tmp
LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\link.EXE"' : return code '0x49d'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

--- openssl 1.1.0 installation failed ---`

**Comment by mmcs85** [comment]
Nice!! If you got the latest version is not building yet. I'm fixing the eos 3.0 alpha version to compile with MSVC. Please be patient and if you do a fix create a PR. Thanks
