### ISSUE TITLE
GetText will not Install.

### ISSUE THREAD

**Issue by Babaloncryptolog** [mmcs85/eos#4]
Getting gettext 0.19.8 from http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.tar.gz

Extracting gettext 0.19.8

Can't locate Archive/Extract.pm in @INC (you may need to install the Archive::Extract
site/lib C:/Perl64/lib).
BEGIN failed--compilation aborted.
Creating cmake configuration for gettext-0.19.8

Copy-Item : Could not find a part of the path 'C:\Users\Kyzitemelos93\extdeps\gettext-
At C:\Users\Kyzitemelos93\eos\build.ps1:204 char:3
+         Copy-Item "scripts\msvc-configs\gettext-0.19.8\cmake.in" "$ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundExceptio
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShel

Copy-Item : Could not find a part of the path 'C:\Users\Kyzitemelos93\extdeps\gettext-
At C:\Users\Kyzitemelos93\eos\build.ps1:205 char:3
+         Copy-Item "scripts\msvc-configs\gettext-0.19.8\config.h" "$ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundExceptio
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShel

Copy-Item : Could not find a part of the path 'C:\Users\Kyzitemelos93\extdeps\gettext-
At C:\Users\Kyzitemelos93\eos\build.ps1:206 char:3
+         Copy-Item "scripts\msvc-configs\gettext-0.19.8\libgnuintl.h"  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundExceptio
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShel

Configuring gettext 0.19.8

pushd : Cannot find path 'C:\Users\Kyzitemelos93\extdeps\gettext-0.19.8' because it do
At C:\Users\Kyzitemelos93\eos\build.ps1:211 char:3
+         pushd ("$extPath\gettext-0.19.8")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Kyzite...\gettext-0.19.8:Strin
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.PushLocationC

-- The C compiler identification is MSVC 19.12.25835.0
-- The CXX compiler identification is MSVC 19.12.25835.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/C
/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/C
/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017
27/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017
27/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:26 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:30 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:68 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using custom FindBoost.cmake
CMake Warning (dev) at libraries/fc/CMakeModules/FindBoost.cmake:347 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  libraries/fc/CMakeModules/FindBoost.cmake:758 (_Boost_GUESS_COMPILER_PREFIX)
  CMakeLists.txt:75 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1132 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:75 (FIND_PACKAGE)

-- Configuring Eos on WIN32
-- tcl INCLUDE PATH: /include
-- Could NOT find Tclsh (missing: TCL_TCLSH)
-- Could NOT find TCL (missing: TCL_LIBRARY)
-- Could NOT find TCLTK (missing: TCL_LIBRARY TK_LIBRARY TK_INCLUDE_PATH)
-- Could NOT find TK (missing: TK_LIBRARY TK_INCLUDE_PATH)
-- tcl_library: TCL_LIBRARY-NOTFOUND
-- --------------------------------------------------------------------
-- No WASM compiler could be found ... (skipping building of contracts)
-- --------------------------------------------------------------------
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStanda
  Could NOT find Secp256k1 (missing: Secp256k1_INCLUDE_DIR Secp256k1_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:
  libraries/fc/CMakeModules/FindSecp256k1.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libraries/fc/CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Kyzitemelos93/eos/build/4c452c40-51e2-4243-b93f-f789398d6343/CMakeF

Building gettext 0.19.8

Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj

--- gettext-0.19.8 installation failed ---

**Comment by mmcs85** [comment]
Can't locate Archive/Extract.pm in @inc (you may need to install the Archive::Extract
site/lib C:/Perl64/lib).

This means you need to install the archive extract module.

Type in a new powershell console:
ppm install Archive-Extract
