### ISSUE TITLE
NASM not found - please read INSTALL and NOTES.WIN for further details

### ISSUE THREAD

**Issue by Babaloncryptolog** [mmcs85/eos#5]
Running Build.ps1 once again and all looks good now with the exception of Powershell 
not recognizing NASM. 
I have previously installed the NASM.exe for window x64 and for some reason it will not run. 

I appologize for the continuous Issues however I would really like to run EOS on windows and greatly appreciate your work building a windows friendly script.

**Comment by mmcs85** [comment]
This is related to the system environment variable "path" not having the path to NASM when you installed it should have been added.

![image](https://user-images.githubusercontent.com/19377179/37653281-30f3a6e8-2c36-11e8-8cbf-4f92ca7d6561.png)

1 - Add in system variables > path variable "C:\Program Files\NASM" to the end separated by ;
2 - Make sure NASM exists in the given path

PS: The latest version of the master branch is currently under development to support DAWN 3.0 so expect errors later on.
also build.ps1 changed to eosio_build.ps1
